4th module

In [8]:
#filling arrays with numpy
import numpy as np 
arr=np.array([1,2,3,4,5,6,7,8,9,10],ndmin=10)
print(arr)

[[[[[[[[[[ 1  2  3  4  5  6  7  8  9 10]]]]]]]]]]


In [11]:
arr=np.array(([1,2,3,4,5,6,7,8,9,10]))
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [19]:
arr=np.ones=(2)
print(arr)

2


In [2]:
import numpy as np
arr=np.ones(10)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [3]:
arr=np.ones((50,50))
print(arr)

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


In [10]:
arr=np.ones((51,51))
print(arr)

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


In [4]:
arr=np.arrange=(10,11)
print(arr)

(10, 11)


In [11]:
arr=np.array(['banana','grapes','apple'])
print(arr)

['banana' 'grapes' 'apple']


In [13]:
arr=np.array([2,3,4,5,6,7,8,9])

sorted_array=array=np.sort(arr)
print(sorted_array)

[2 3 4 5 6 7 8 9]


In [14]:
arr=np.array(['alpa','beta','gama','rays'])

sorted_array=array=np.sort(arr)
print(sorted_array)

['alpa' 'beta' 'gama' 'rays']


In [5]:
import numpy as np

arr = np.ones((4,8,3))
print(arr)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


access array elements

sorting 2d array

In [15]:
arr=np.array([[6,2,3],[9,5,6]])
print( np.sort(arr) )

[[2 3 6]
 [5 6 9]]


Accessing Array elements

In [4]:
import numpy as np
arr = np.array([1,2,3,5,6])

print(arr[-2:])


[5 6]


In [5]:
import numpy as np
arr = np.array([1,2,3,5,6,7,8])

print(arr[-5:-1])

[3 5 6 7]


In [12]:
arr = np.array([1,2,3,5,6,7,8])

print(arr[-5:4])

[3 5]


In [14]:
arr = np.array([10,20,30,50,60,70,80])

print(arr[0:7])

[10 20 30 50 60 70 80]


In [15]:
arr = np.array([10,20,30,50,60,70,80])

print(arr[3:5])

[50 60]


In [27]:
mat=np.array([[10,20,21,22,25],[30,40,41,42,43]])
print(mat)
print(mat[1,2])

[[10 20 21 22 25]
 [30 40 41 42 43]]
41


3d array

In [41]:
import numpy as np
mat=np.array([  [[21,22,25],[41,42,43]]  ,  [[50,51,52],[60,61,62]]  ])
print(mat)
print("value:",mat[1,1,2])

[[[21 22 25]
  [41 42 43]]

 [[50 51 52]
  [60 61 62]]]
value: 62


In [43]:
arr=np.array([1,2,3,4,5,6])

print(arr[1:6:2])

[2 4 6]


In [50]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr[1,1:4])

[6 7 8]


searching in array 

In [51]:
arr=np.array([2,50,40,60,70])

val=np.where(arr==40)
print(val)

(array([2], dtype=int64),)


In [56]:
arr=np.array([1,2,3,4,5,])

val=np.where(arr%3==0)
print(val)

(array([2], dtype=int64),)


searchsorted()

In [57]:
arr=np.array([10,20,50,60])

val=np.searchsorted(arr,8)
val

0

In [59]:
arr=np.array([6,7,9,19])
x=np.searchsorted(arr,8)
print(x)

2


In [60]:
np.searchsorted([1,2,3,4,5],3)

2

In [61]:
np.searchsorted([1,2,3,4,5],3,side='right')

3

In [ ]:
np.searchsorted([1,2,3,4,5],)

In [9]:
import numpy as np
arr=np.array(10,20,50,60)
val=np.searchsorted(arr[-10,40,55])
val

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

reshaping array: reshape()

In [64]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
rs=arr.reshape(4,3)
rs

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [67]:
arr=np.array([[1,2],[3,4]])
print(arr.reshape(-1))                   #converting 2d into 1d

[1 2 3 4]


Filtering array: Filter()